[2021-10-13 22:52:35,928] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table manual__2021-10-13T22:50:14.704120+00:00 [queued]>
[2021-10-13 22:52:35,938] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table manual__2021-10-13T22:50:14.704120+00:00 [queued]>
[2021-10-13 22:52:35,939] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:52:35,939] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-10-13 22:52:35,939] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:52:35,952] {taskinstance.py:1262} INFO - Executing <Task(SqliteOperator): creating_table> on 2021-10-13 22:50:14.704120+00:00
[2021-10-13 22:52:35,956] {standard_task_runner.py:52} INFO - Started process 2071 to run task
[2021-10-13 22:52:35,959] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'creating_table', 'manual__2021-10-13T22:50:14.704120+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpa4ni4608', '--error-file', '/tmp/tmp_cgv4cm4']
[2021-10-13 22:52:35,959] {standard_task_runner.py:77} INFO - Job 24: Subtask creating_table
[2021-10-13 22:52:35,998] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.creating_table manual__2021-10-13T22:50:14.704120+00:00 [running]> on host 981af2cc3d86
[2021-10-13 22:52:36,040] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T22:50:14.704120+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T22:50:14.704120+00:00
[2021-10-13 22:52:36,041] {sqlite.py:61} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
                first_name TEXT NOT NULL,
                last_name TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
        
[2021-10-13 22:52:36,047] {base.py:79} INFO - Using connection to: id: db_sqlite. Host: /opt/***/***.db, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-10-13 22:52:36,048] {dbapi.py:225} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                first_name TEXT NOT NULL,
                last_name TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
        , parameters: []
[2021-10-13 22:52:36,057] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=creating_table, execution_date=20211013T225014, start_date=20211013T225235, end_date=20211013T225236
[2021-10-13 22:52:36,091] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 22:52:36,128] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
