[2021-10-13 22:45:27,880] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user scheduled__2021-10-12T00:00:00+00:00 [queued]>
[2021-10-13 22:45:27,889] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user scheduled__2021-10-12T00:00:00+00:00 [queued]>
[2021-10-13 22:45:27,889] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:45:27,889] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-10-13 22:45:27,889] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:45:27,902] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): storing_user> on 2021-10-12 00:00:00+00:00
[2021-10-13 22:45:27,905] {standard_task_runner.py:52} INFO - Started process 1686 to run task
[2021-10-13 22:45:27,908] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'storing_user', 'scheduled__2021-10-12T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpmfit2xo1', '--error-file', '/tmp/tmpostiytir']
[2021-10-13 22:45:27,908] {standard_task_runner.py:77} INFO - Job 13: Subtask storing_user
[2021-10-13 22:45:27,937] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.storing_user scheduled__2021-10-12T00:00:00+00:00 [running]> on host 981af2cc3d86
[2021-10-13 22:45:27,972] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=storing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-12T00:00:00+00:00
[2021-10-13 22:45:27,973] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-10-13 22:45:27,974] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo -e ".separator ","\n.import /tmp/processed_user.csv users" | sqlite3 /opt/***/***.db']
[2021-10-13 22:45:27,981] {subprocess.py:85} INFO - Output:
[2021-10-13 22:45:27,986] {subprocess.py:93} INFO - Command exited with return code 0
[2021-10-13 22:45:28,003] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=storing_user, execution_date=20211012T000000, start_date=20211013T224527, end_date=20211013T224528
[2021-10-13 22:45:28,039] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 22:45:28,060] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-13 22:52:40,336] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user manual__2021-10-13T22:50:14.704120+00:00 [queued]>
[2021-10-13 22:52:40,346] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user manual__2021-10-13T22:50:14.704120+00:00 [queued]>
[2021-10-13 22:52:40,347] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:52:40,347] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-10-13 22:52:40,347] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:52:40,360] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): storing_user> on 2021-10-13 22:50:14.704120+00:00
[2021-10-13 22:52:40,364] {standard_task_runner.py:52} INFO - Started process 2079 to run task
[2021-10-13 22:52:40,367] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'storing_user', 'manual__2021-10-13T22:50:14.704120+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp2tu3agys', '--error-file', '/tmp/tmp8u07x9k0']
[2021-10-13 22:52:40,367] {standard_task_runner.py:77} INFO - Job 28: Subtask storing_user
[2021-10-13 22:52:40,399] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.storing_user manual__2021-10-13T22:50:14.704120+00:00 [running]> on host 981af2cc3d86
[2021-10-13 22:52:40,440] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=storing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T22:50:14.704120+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T22:50:14.704120+00:00
[2021-10-13 22:52:40,440] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-10-13 22:52:40,441] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo -e ".separator ","\n.import /tmp/processed_user.csv users" | sqlite3 /opt/***/***.db']
[2021-10-13 22:52:40,448] {subprocess.py:85} INFO - Output:
[2021-10-13 22:52:40,454] {subprocess.py:93} INFO - Command exited with return code 0
[2021-10-13 22:52:40,485] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=storing_user, execution_date=20211013T225014, start_date=20211013T225240, end_date=20211013T225240
[2021-10-13 22:52:40,538] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 22:52:40,573] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
