[2021-10-13 22:44:28,345] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user scheduled__2021-10-12T00:00:00+00:00 [queued]>
[2021-10-13 22:44:28,353] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user scheduled__2021-10-12T00:00:00+00:00 [queued]>
[2021-10-13 22:44:28,354] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:44:28,354] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 22:44:28,354] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:44:28,367] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-12 00:00:00+00:00
[2021-10-13 22:44:28,370] {standard_task_runner.py:52} INFO - Started process 1628 to run task
[2021-10-13 22:44:28,373] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'scheduled__2021-10-12T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpc3v9ehag', '--error-file', '/tmp/tmp877_lr61']
[2021-10-13 22:44:28,373] {standard_task_runner.py:77} INFO - Job 11: Subtask processing_user
[2021-10-13 22:44:28,403] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user scheduled__2021-10-12T00:00:00+00:00 [running]> on host 981af2cc3d86
[2021-10-13 22:44:28,438] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-12T00:00:00+00:00
[2021-10-13 22:44:28,457] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 22:44:28,466] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211012T000000, start_date=20211013T224428, end_date=20211013T224428
[2021-10-13 22:44:28,504] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 22:44:28,536] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-13 22:46:49,862] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T22:46:45.545139+00:00 [queued]>
[2021-10-13 22:46:49,872] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T22:46:45.545139+00:00 [queued]>
[2021-10-13 22:46:49,872] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:46:49,872] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 22:46:49,872] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:46:49,884] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 22:46:45.545139+00:00
[2021-10-13 22:46:49,888] {standard_task_runner.py:52} INFO - Started process 1758 to run task
[2021-10-13 22:46:49,891] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T22:46:45.545139+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpa_huhv14', '--error-file', '/tmp/tmpoqe4zxid']
[2021-10-13 22:46:49,891] {standard_task_runner.py:77} INFO - Job 17: Subtask processing_user
[2021-10-13 22:46:49,921] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T22:46:45.545139+00:00 [running]> on host 981af2cc3d86
[2021-10-13 22:46:49,956] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T22:46:45.545139+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T22:46:45.545139+00:00
[2021-10-13 22:46:49,970] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 22:46:49,980] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T224645, start_date=20211013T224649, end_date=20211013T224649
[2021-10-13 22:46:50,022] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 22:46:50,051] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-13 22:50:18,873] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T22:50:14.704120+00:00 [queued]>
[2021-10-13 22:50:18,882] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T22:50:14.704120+00:00 [queued]>
[2021-10-13 22:50:18,882] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:50:18,882] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 22:50:18,882] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:50:18,894] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 22:50:14.704120+00:00
[2021-10-13 22:50:18,898] {standard_task_runner.py:52} INFO - Started process 1950 to run task
[2021-10-13 22:50:18,901] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T22:50:14.704120+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmplag2bi_t', '--error-file', '/tmp/tmp_wkssv9h']
[2021-10-13 22:50:18,901] {standard_task_runner.py:77} INFO - Job 22: Subtask processing_user
[2021-10-13 22:50:18,930] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T22:50:14.704120+00:00 [running]> on host 981af2cc3d86
[2021-10-13 22:50:18,968] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T22:50:14.704120+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T22:50:14.704120+00:00
[2021-10-13 22:50:18,980] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 22:50:18,989] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T225014, start_date=20211013T225018, end_date=20211013T225018
[2021-10-13 22:50:19,032] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 22:50:19,072] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-13 22:56:03,186] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T22:55:58.466781+00:00 [queued]>
[2021-10-13 22:56:03,195] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T22:55:58.466781+00:00 [queued]>
[2021-10-13 22:56:03,195] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:56:03,196] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 22:56:03,196] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:56:03,208] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 22:55:58.466781+00:00
[2021-10-13 22:56:03,212] {standard_task_runner.py:52} INFO - Started process 2256 to run task
[2021-10-13 22:56:03,214] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T22:55:58.466781+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpf__dp0qy', '--error-file', '/tmp/tmp4dfgbd0m']
[2021-10-13 22:56:03,214] {standard_task_runner.py:77} INFO - Job 33: Subtask processing_user
[2021-10-13 22:56:03,243] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T22:55:58.466781+00:00 [running]> on host 981af2cc3d86
[2021-10-13 22:56:03,276] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T22:55:58.466781+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T22:55:58.466781+00:00
[2021-10-13 22:56:03,287] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 22:56:03,296] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T225558, start_date=20211013T225603, end_date=20211013T225603
[2021-10-13 22:56:03,345] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 22:56:03,368] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-13 23:04:38,723] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:04:35.053372+00:00 [queued]>
[2021-10-13 23:04:38,733] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:04:35.053372+00:00 [queued]>
[2021-10-13 23:04:38,733] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:04:38,733] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 23:04:38,733] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:04:38,745] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 23:04:35.053372+00:00
[2021-10-13 23:04:38,749] {standard_task_runner.py:52} INFO - Started process 2691 to run task
[2021-10-13 23:04:38,751] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T23:04:35.053372+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpmoc2tc_i', '--error-file', '/tmp/tmpd6i7wayg']
[2021-10-13 23:04:38,751] {standard_task_runner.py:77} INFO - Job 38: Subtask processing_user
[2021-10-13 23:04:38,782] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T23:04:35.053372+00:00 [running]> on host 981af2cc3d86
[2021-10-13 23:04:38,818] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T23:04:35.053372+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T23:04:35.053372+00:00
[2021-10-13 23:04:38,831] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 23:04:38,839] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T230435, start_date=20211013T230438, end_date=20211013T230438
[2021-10-13 23:04:38,882] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 23:04:38,917] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-13 23:07:13,402] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:07:09.307371+00:00 [queued]>
[2021-10-13 23:07:13,411] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:07:09.307371+00:00 [queued]>
[2021-10-13 23:07:13,411] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:07:13,411] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 23:07:13,411] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:07:13,424] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 23:07:09.307371+00:00
[2021-10-13 23:07:13,427] {standard_task_runner.py:52} INFO - Started process 2844 to run task
[2021-10-13 23:07:13,429] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T23:07:09.307371+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpjhkjbggs', '--error-file', '/tmp/tmpkrauvlvn']
[2021-10-13 23:07:13,430] {standard_task_runner.py:77} INFO - Job 44: Subtask processing_user
[2021-10-13 23:07:13,457] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T23:07:09.307371+00:00 [running]> on host 981af2cc3d86
[2021-10-13 23:07:13,490] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T23:07:09.307371+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T23:07:09.307371+00:00
[2021-10-13 23:07:13,500] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 23:07:13,508] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T230709, start_date=20211013T230713, end_date=20211013T230713
[2021-10-13 23:07:13,521] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 23:07:13,543] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-13 23:11:37,055] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:11:32.382439+00:00 [queued]>
[2021-10-13 23:11:37,065] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:11:32.382439+00:00 [queued]>
[2021-10-13 23:11:37,065] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:11:37,065] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 23:11:37,065] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:11:37,077] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 23:11:32.382439+00:00
[2021-10-13 23:11:37,081] {standard_task_runner.py:52} INFO - Started process 3078 to run task
[2021-10-13 23:11:37,083] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T23:11:32.382439+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpzj7zmvr6', '--error-file', '/tmp/tmpuygcmlcc']
[2021-10-13 23:11:37,083] {standard_task_runner.py:77} INFO - Job 49: Subtask processing_user
[2021-10-13 23:11:37,110] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T23:11:32.382439+00:00 [running]> on host 981af2cc3d86
[2021-10-13 23:11:37,142] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T23:11:32.382439+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T23:11:32.382439+00:00
[2021-10-13 23:11:37,153] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 23:11:37,161] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T231132, start_date=20211013T231137, end_date=20211013T231137
[2021-10-13 23:11:37,174] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 23:11:37,205] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-13 23:28:34,389] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:28:30.245822+00:00 [queued]>
[2021-10-13 23:28:34,398] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:28:30.245822+00:00 [queued]>
[2021-10-13 23:28:34,398] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:28:34,398] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 23:28:34,398] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:28:34,412] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 23:28:30.245822+00:00
[2021-10-13 23:28:34,416] {standard_task_runner.py:52} INFO - Started process 3949 to run task
[2021-10-13 23:28:34,418] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T23:28:30.245822+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp9e0n2sih', '--error-file', '/tmp/tmp6pcci05q']
[2021-10-13 23:28:34,419] {standard_task_runner.py:77} INFO - Job 54: Subtask processing_user
[2021-10-13 23:28:34,449] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T23:28:30.245822+00:00 [running]> on host 981af2cc3d86
[2021-10-13 23:28:34,484] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T23:28:30.245822+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T23:28:30.245822+00:00
[2021-10-13 23:28:34,496] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 23:28:34,504] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T232830, start_date=20211013T232834, end_date=20211013T232834
[2021-10-13 23:28:34,550] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 23:28:34,574] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-13 23:36:59,973] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:36:55.176601+00:00 [queued]>
[2021-10-13 23:36:59,981] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:36:55.176601+00:00 [queued]>
[2021-10-13 23:36:59,981] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:36:59,982] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 23:36:59,982] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:36:59,994] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 23:36:55.176601+00:00
[2021-10-13 23:36:59,997] {standard_task_runner.py:52} INFO - Started process 4384 to run task
[2021-10-13 23:36:59,999] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T23:36:55.176601+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpwug0y600', '--error-file', '/tmp/tmpf2t1imo5']
[2021-10-13 23:37:00,000] {standard_task_runner.py:77} INFO - Job 62: Subtask processing_user
[2021-10-13 23:37:00,028] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T23:36:55.176601+00:00 [running]> on host 981af2cc3d86
[2021-10-13 23:37:00,062] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T23:36:55.176601+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T23:36:55.176601+00:00
[2021-10-13 23:37:00,076] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 23:37:00,086] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T233655, start_date=20211013T233659, end_date=20211013T233700
[2021-10-13 23:37:00,131] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 23:37:00,160] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-13 23:42:01,807] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:41:56.381369+00:00 [queued]>
[2021-10-13 23:42:01,817] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:41:56.381369+00:00 [queued]>
[2021-10-13 23:42:01,817] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:42:01,817] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 23:42:01,817] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:42:01,830] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 23:41:56.381369+00:00
[2021-10-13 23:42:01,834] {standard_task_runner.py:52} INFO - Started process 4648 to run task
[2021-10-13 23:42:01,837] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T23:41:56.381369+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp0ptgyo_6', '--error-file', '/tmp/tmpmgwxbjai']
[2021-10-13 23:42:01,837] {standard_task_runner.py:77} INFO - Job 7: Subtask processing_user
[2021-10-13 23:42:01,866] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T23:41:56.381369+00:00 [running]> on host 981af2cc3d86
[2021-10-13 23:42:01,904] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T23:41:56.381369+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T23:41:56.381369+00:00
[2021-10-13 23:42:01,917] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 23:42:01,926] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T234156, start_date=20211013T234201, end_date=20211013T234201
[2021-10-13 23:42:01,968] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 23:42:02,001] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-13 23:42:40,630] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:42:35.932211+00:00 [queued]>
[2021-10-13 23:42:40,640] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:42:35.932211+00:00 [queued]>
[2021-10-13 23:42:40,640] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:42:40,640] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 23:42:40,640] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:42:40,653] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 23:42:35.932211+00:00
[2021-10-13 23:42:40,657] {standard_task_runner.py:52} INFO - Started process 4694 to run task
[2021-10-13 23:42:40,660] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T23:42:35.932211+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpli0rhygz', '--error-file', '/tmp/tmpdhfiecog']
[2021-10-13 23:42:40,660] {standard_task_runner.py:77} INFO - Job 12: Subtask processing_user
[2021-10-13 23:42:40,690] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T23:42:35.932211+00:00 [running]> on host 981af2cc3d86
[2021-10-13 23:42:40,728] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T23:42:35.932211+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T23:42:35.932211+00:00
[2021-10-13 23:42:40,742] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 23:42:40,753] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T234235, start_date=20211013T234240, end_date=20211013T234240
[2021-10-13 23:42:40,791] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 23:42:40,826] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-13 23:43:29,928] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:43:24.490456+00:00 [queued]>
[2021-10-13 23:43:29,938] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T23:43:24.490456+00:00 [queued]>
[2021-10-13 23:43:29,938] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:43:29,938] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-13 23:43:29,938] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 23:43:29,951] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 23:43:24.490456+00:00
[2021-10-13 23:43:29,955] {standard_task_runner.py:52} INFO - Started process 4752 to run task
[2021-10-13 23:43:29,958] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T23:43:24.490456+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmppvmhw2vl', '--error-file', '/tmp/tmp2o9q2qch']
[2021-10-13 23:43:29,958] {standard_task_runner.py:77} INFO - Job 17: Subtask processing_user
[2021-10-13 23:43:29,988] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T23:43:24.490456+00:00 [running]> on host 981af2cc3d86
[2021-10-13 23:43:30,022] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T23:43:24.490456+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T23:43:24.490456+00:00
[2021-10-13 23:43:30,034] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 23:43:30,045] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T234324, start_date=20211013T234329, end_date=20211013T234330
[2021-10-13 23:43:30,089] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 23:43:30,120] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
